import image from "./../../../../assets/Avatar1.png";
import image2 from "./../../../../assets/Avatar2.png";
import image3 from "./../../../../assets/Avatar3.png";
import BookingTable, {
  BookingDataSeller,
} from "./components/Table/BookingTable";

export default function BookingManagementPage() {
  const data: BookingDataSeller[] = [
    {
      id: 1,
      title: "هتل سراوان",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 150000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "تایید شده",
      payment_status: "لغو شده",
      image: image.src,
    },
    {
      id: 2,
      title: "شیراز پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 150000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "تایید شده",
      image: image2.src,
    },
    {
      id: 3,
      title: "تراول پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 160000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "لغو شده",
      image: image3.src,
    },
    {
      id: 4,
      title: "میدان جمهریه",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 180000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "تایید شده",
      payment_status: "لغو شده",
      image: image2.src,
    },
    {
      id: 5,
      title: "ماهی پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 170000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "تایید شده",
      image: image3.src,
    },
    {
      id: 6,
      title: "کوه سراوان",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 170000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "لغو شده",
      image: image2.src,
    },
    {
      id: 7,
      title: "ساحل سراوان",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 100000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "تایید شده",
      image: image.src,
    },
    {
      id: 8,
      title: "ماهی پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 160000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "تایید شده",
      image: image2.src,
    },
    {
      id: 9,
      title: "ماهی پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 190000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "تایید شده",
      payment_status: "لغو شده",
      image: image3.src,
    },
    {
      id: 10,
      title: "نسرین پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 170000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "تایید شده",
      image: image2.src,
    },
    {
      id: 11,
      title: "ماهی پارک",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 170000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "لغو شده",
      image: image.src,
    },
    {
      id: 12,
      title: "ساحل سراوان",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 170000000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "در انتظار",
      payment_status: "تایید شده",
      image: image3.src,
    },
    {
      id: 13,
      title: "ماهی بهشهر",
      title2: " سبحان عرب خزائلی ،4/1/8...",
      date: "1403/02/01/ 10:00",
      price: 186600000,
      passengers: "سبحان عرب خزائلی ،4/1/8...",
      status: "تایید شده",
      payment_status: "لغو شده",
      image: image2.src,
    },
  ];

  return <BookingTable bookingDataSeller={data} />;
}
