import { SessionProvider } from "next-auth/react";
import QueryProvider from "@/utils/providers/providers";
import { Providers } from "@/utils/providers/ProvidersHeroUi";
import localFont from "next/font/local";
import { Metadata } from "next";
import "./globals.css";
import { auth } from "@/services/auth";
import ClientLayout from "./ClientLayout";

const vazirmatn = localFont({
  src: "./../assets/fonts/Vazirmatn.ttf",
  variable: "--font-vazirmatn",
  display: "swap",
});
export const metadata: Metadata = {
  title: "BUYORENT",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        <SessionProvider session={session}>
          <QueryProvider>
            <Providers>{children}</Providers>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
