import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import QueryProvider from "@/utils/providers";
import { Providers } from "./ProvidersHeroUi";

const vazirmatn = localFont({
  src: "./../assets/fonts/Vazirmatn.ttf",
  variable: "--font-vazirmatn",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        <SessionProvider session={session}>
          <QueryProvider>
            <Providers> {children}</Providers>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
